// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mavenlink-jira-sync/mavenlink-jira-sync.proto

package mavenlink_jira_sync

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnvironmentConfiguration struct {
	Debug                bool     `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
	Master               string   `protobuf:"bytes,2,opt,name=master,proto3" json:"master,omitempty"`
	Strict               bool     `protobuf:"varint,3,opt,name=strict,proto3" json:"strict,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvironmentConfiguration) Reset()         { *m = EnvironmentConfiguration{} }
func (m *EnvironmentConfiguration) String() string { return proto.CompactTextString(m) }
func (*EnvironmentConfiguration) ProtoMessage()    {}
func (*EnvironmentConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_jira_sync_7502bd6714d1c71f, []int{0}
}
func (m *EnvironmentConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvironmentConfiguration.Unmarshal(m, b)
}
func (m *EnvironmentConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvironmentConfiguration.Marshal(b, m, deterministic)
}
func (dst *EnvironmentConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvironmentConfiguration.Merge(dst, src)
}
func (m *EnvironmentConfiguration) XXX_Size() int {
	return xxx_messageInfo_EnvironmentConfiguration.Size(m)
}
func (m *EnvironmentConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvironmentConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_EnvironmentConfiguration proto.InternalMessageInfo

func (m *EnvironmentConfiguration) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *EnvironmentConfiguration) GetMaster() string {
	if m != nil {
		return m.Master
	}
	return ""
}

func (m *EnvironmentConfiguration) GetStrict() bool {
	if m != nil {
		return m.Strict
	}
	return false
}

type EquivalenceTypes struct {
	IssueType            bool     `protobuf:"varint,1,opt,name=issueType,proto3" json:"issueType,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Priority             bool     `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EquivalenceTypes) Reset()         { *m = EquivalenceTypes{} }
func (m *EquivalenceTypes) String() string { return proto.CompactTextString(m) }
func (*EquivalenceTypes) ProtoMessage()    {}
func (*EquivalenceTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_mavenlink_jira_sync_7502bd6714d1c71f, []int{1}
}
func (m *EquivalenceTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquivalenceTypes.Unmarshal(m, b)
}
func (m *EquivalenceTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquivalenceTypes.Marshal(b, m, deterministic)
}
func (dst *EquivalenceTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquivalenceTypes.Merge(dst, src)
}
func (m *EquivalenceTypes) XXX_Size() int {
	return xxx_messageInfo_EquivalenceTypes.Size(m)
}
func (m *EquivalenceTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_EquivalenceTypes.DiscardUnknown(m)
}

var xxx_messageInfo_EquivalenceTypes proto.InternalMessageInfo

func (m *EquivalenceTypes) GetIssueType() bool {
	if m != nil {
		return m.IssueType
	}
	return false
}

func (m *EquivalenceTypes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *EquivalenceTypes) GetPriority() bool {
	if m != nil {
		return m.Priority
	}
	return false
}

func init() {
	proto.RegisterType((*EnvironmentConfiguration)(nil), "EnvironmentConfiguration")
	proto.RegisterType((*EquivalenceTypes)(nil), "EquivalenceTypes")
}

func init() {
	proto.RegisterFile("proto/mavenlink-jira-sync/mavenlink-jira-sync.proto", fileDescriptor_mavenlink_jira_sync_7502bd6714d1c71f)
}

var fileDescriptor_mavenlink_jira_sync_7502bd6714d1c71f = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0x41, 0x6a, 0x85, 0x30,
	0x10, 0x06, 0x60, 0x6c, 0xa9, 0x68, 0x56, 0x25, 0x94, 0x12, 0x4a, 0x17, 0xe2, 0xca, 0x8d, 0xed,
	0xc2, 0x23, 0x14, 0x2f, 0x20, 0x3d, 0x40, 0xa3, 0xa6, 0x32, 0xad, 0x4e, 0xec, 0x64, 0x22, 0x78,
	0xfb, 0x62, 0x0c, 0xef, 0x6d, 0xde, 0xf2, 0xfb, 0x19, 0xfe, 0x9f, 0x11, 0xcd, 0x4a, 0x96, 0xed,
	0xfb, 0xa2, 0x37, 0x83, 0x33, 0xe0, 0x6f, 0xfd, 0x03, 0xa4, 0x6b, 0xb7, 0xe3, 0x70, 0x2b, 0x7b,
	0x0b, 0xd7, 0xe5, 0x97, 0x50, 0x2d, 0x6e, 0x40, 0x16, 0x17, 0x83, 0xfc, 0x61, 0xf1, 0x1b, 0x26,
	0x4f, 0x9a, 0xc1, 0xa2, 0x7c, 0x12, 0x0f, 0xa3, 0xe9, 0xfd, 0xa4, 0x92, 0x22, 0xa9, 0xb2, 0xee,
	0x84, 0x7c, 0x16, 0xe9, 0xa2, 0x1d, 0x1b, 0x52, 0x77, 0x45, 0x52, 0xe5, 0x5d, 0xd4, 0x91, 0x3b,
	0x26, 0x18, 0x58, 0xdd, 0x87, 0xf3, 0xa8, 0x72, 0x14, 0x8f, 0xed, 0x9f, 0x87, 0x4d, 0xcf, 0x06,
	0x07, 0xf3, 0xb9, 0xaf, 0xc6, 0xc9, 0x57, 0x91, 0x83, 0x73, 0x3e, 0x28, 0xb6, 0x5f, 0x83, 0xb3,
	0x49, 0xb3, 0x77, 0x61, 0x21, 0x34, 0x1d, 0x92, 0x2f, 0x22, 0x5b, 0x09, 0x2c, 0x01, 0xef, 0x71,
	0xe3, 0xe2, 0x3e, 0x0d, 0xef, 0x34, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x63, 0xf1, 0x13, 0x99,
	0x05, 0x01, 0x00, 0x00,
}
